Repository mesosphere/dklb, pull requests merged in 2019-02, with the labels that each got.

#13 docs: fix annotation name
  docs/usage/11-provisioning-tcp-cloud-loadbalancers.adoc
Labels: bug, docs

#15 translator: request dynamic stats port
  RELEASE-NOTES.adoc
  docs/design/tcp-and-http-load-balancing.adoc
  pkg/translator/ingress_translator.go
  pkg/translator/ingress_translator_internal_test.go
  pkg/translator/service_translator.go
  pkg/translator/service_translator_internal_test.go
Labels: enhancement

#16 translator: support https-enabled l7 backends
  RELEASE-NOTES.adoc
  pkg/constants/edgelb.go
  pkg/translator/ingress_utils.go
  test/e2e/ingress_test.go
Labels: bug, enhancement

#17 translator: prioritize more specific ingress rules
  RELEASE-NOTES.adoc
  docs/design/tcp-and-http-load-balancing.adoc
  pkg/translator/ingress_utils.go
  test/e2e/ingress_test.go
Labels: bug, enhancement

#19 docs: include prs on release notes
  RELEASE-NOTES.adoc
Labels: docs

#20 controllers: use a single event recorder
  RELEASE-NOTES.adoc
  cmd/main.go
  pkg/controllers/ingress.go
  pkg/controllers/service.go
  pkg/util/kubernetes/events.go
Labels: bug
